### ISSUE TITLE
Support for multiple regions

### ISSUE THREAD

**Issue by rahuldroy** [aws/aws-sdk-php-zf2#21]
I can't seem to find the documentation to specify regions in the module configurations for different services. I use Sydney (ap-southeast-2) for all services such as EC2 & S3. I use Ireland for SES (eu-west-1).

I tried the following, but that didn't work either
```php
return array(
    'aws' => array(
        'key'    => '',
        'secret' => '',

        'services' => array(
            'ses' => array(
                'params' => array(
                    'region' => 'eu-west-1'
                )
            ),
            's3' => array(
                'params' => array(
                    'region' => 'ap-southeast-2'
                )
            ),
        )
    )
);
```

**Comment by jeremeamia** [comment]
I apologize for not responding to the issue.

Using different regions per service can be best accomplished using a config file. See https://github.com/aws/aws-sdk-php-zf2/blob/master/config/aws.local.php.dist#L14-L18.
