### ISSUE TITLE
Update composer.json with 3.* version of aws-sdk-php

### ISSUE THREAD

**Issue by jeremyquinton** [aws/aws-sdk-php-zf2#24]
Currently this module is pegged at aws-sdk-php version 2.*
https://github.com/aws/aws-sdk-php-zf2/blob/master/composer.json#L9

However version 3.0.3 of the aws-sdk-php exists but I can't upgrade because of the above. 
https://github.com/aws/aws-sdk-php/tree/3.0.3

I have a problem with SQS that I think might be fixed with version 3 of the aws-sdk-php. Happy to do a PR on this module to resolve it.

**Comment by jeremeamia** [comment]
There is a bit more work involved to update this module to work with Version 3 of the SDK. See PR #23, which is a work in progress.

If you have an issue using SQS, why don't you report that on the [main SDK repo](https://github.com/aws/aws-sdk-php).

**Comment by jeremyquinton** [comment]
Thanks for the reply. I'll  report the issue there if one doesn't already exist but wanted to first see if using version 3.0 of the SDK would solve the problem. 

Getting an error message "The specified queue does not exist for this wsdl version" which is a little cryptic. Happy if you want to close down this issue as #23 will solve it.

**Comment by jeremeamia** [comment]
@jeremyquinton For that specific issue, it may just be that you need to set the region of the client to match the region of your queue. I'm closing this issue, but feel free to follow up on the main SDK repo if needed. Thanks.

**Comment by jeremyquinton** [comment]
I am setting the region but I'm using a ZF2 Module SlmQueue which then relies on this module. I'll just have to use my debugger to ensure the value I'm using in config is the value that ends up getting used the aws sqs client
