### ISSUE TITLE
problem serviceLocator S3RenameUpload

### ISSUE THREAD

**Issue by apoca** [aws/aws-sdk-php-zf2#30]
In this line:

$filter = $this->getServiceLocator()->get('FilterManager')->get('S3RenameUpload');

I got this error:

An exception was raised while creating "S3RenameUpload"; no instance returned

Someone can help me!?

**Comment by jeskew** [comment]
Hi @apoca,

Sorry for the delay in getting back to you. Are you still seeing this issue?

**Comment by jeskew** [comment]
Closing for now. Please feel free to reopen if you see the issue again.

**Comment by vimalmishra09** [comment]
Hi Jeskew,

I am still facing the same issue. Can you help me?

**Comment by rexatgithub** [comment]
hi @apoca did you able to solve this one? Im experiencing it now.

**Comment by jeskew** [comment]
@rexatgithub Please see #33 for a discussion. ZF2 raises this error when an exception is thrown during service creation.
