### ISSUE TITLE
ServiceNotCreatedException

### ISSUE THREAD

**Issue by vimalmishra09** [aws/aws-sdk-php-zf2#33]
$filter = $this->getServiceLocator()->get('FilterManager')->get('S3RenameUpload');

An exception was raised while creating "S3RenameUpload"; no instance returned

Can some please help?

**Comment by jeskew** [comment]
Make sure you have added an appropriately [configured the module](https://github.com/aws/aws-sdk-php-zf2#configuration). If no configuration is present when you try to load the `S3RenameUpload` filter, then the constructor will through an `InvalidArgumentException` and no instance will be returned. Zf2 catches this exception and returns a `Zend\ServiceManager\Exception\ServiceNotCreatedException`.
