### ISSUE TITLE
Error retrieving credentials from the instance profile metadata server.

### ISSUE THREAD

**Issue by Saeven** [aws/aws-sdk-php-zf2#35]
Does this lib still work with the 3.x branch?  In testing upgrades, despite the setup being done as documented in your readme, end up with errors as shown in the subject:

```
Error retrieving credentials from the instance profile metadata server.
```

Cheers!
Alex

**Comment by jeskew** [comment]
You will need to provide credentials either through the environment (as documented [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html)) or in the package config (as documented [here](https://github.com/aws/aws-sdk-php-zf2#configuration)).

**Comment by cjyclaire** [comment]
I'll close this issue due to ages, feel free to reopen it if you have further questions.

**Comment by nishanthvallambatla** [comment]
Hi,
I am facing the same issue with aws-php-sdk version 3.18.x
