### ISSUE TITLE
PHP Fatal error - version 2.0.2

### ISSUE THREAD

**Issue by MaiKaY** [aws/aws-sdk-php-zf2#37]
Hi guys,
since the release of your version [2.0.2](https://github.com/aws/aws-sdk-php-zf2/releases/tag/2.0.2) i am getting the following **PHP Fatal error**

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to AwsModule\Factory\AwsFactory::__invoke() must be an instance of Interop\Container\ContainerInterface, instance of Zend\ServiceManager\ServiceManager given, called in /Applications/MAMP/htdocs/XXXXX/vendor/aws/aws-sdk-php-zf2/src/Factory/AwsFactory.php on line 44 and defined in /Applications/MAMP/htdocs/XXXXX/vendor/aws/aws-sdk-php-zf2/src/Factory/AwsFactory.php:23

How i try to get for example my S3Client:
```
/**
 * @return \Aws\S3\S3Client
 */
private function getS3Client()
{
    /** @var Sdk $aws */
    $aws = $this->getServiceLocator()->get(Sdk::class);

    return $aws->createS3();
}
```

Why is such a change not a **Breaking Change** which ends in a new minor version (2.1.0)?

best regards
Maik

**Comment by cjyclaire** [comment]
Apologies for the version bump, version tag has been fixed, thank you.

**Comment by cjyclaire** [comment]
Thank you so much for your patience, now fixed!
