### ISSUE TITLE
master branch is incompatible with ZF2

### ISSUE THREAD

**Issue by mikel5** [aws/aws-sdk-php-zf2#41]
The change made in https://github.com/aws/aws-sdk-php-zf2/pull/36 to the AwsModule\Factory\AwsFactory class is incompatible with ZF2 as the ZF2 Service Manager isn't an instance of Interop\Container\ContainerInterface

**Comment by cjyclaire** [comment]
@mikel5 thanks for reporting, I'm looking into the issue, could you use older version as work-around temporary?

**Comment by mikel5** [comment]
Yes.   I've set composer to use version 2.0.*

**Comment by cjyclaire** [comment]
Closing, PR is merged with composer update, if using ZF2 service manager < 2.7, please require `2.0.*` instead. Feel free to reopen if you have further questions.
