### ISSUE TITLE
$sm->get(DynamoDbSaveHandler::class); i got a error

### ISSUE THREAD

**Issue by dovanmanh080485** [aws/aws-sdk-php-zf2#42]
i'm working with zend2. when i try to call on Module.php (getServiceConfig function)

$saveHandler = $sm->get(DynamoDbSaveHandler::class); i got a error

Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 'Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for AwsModule\Session\SaveHandler\DynamoDb ...............

can you help me ?

**Comment by cjyclaire** [comment]
@dovanmanh080485, May I ask which package version are you using? Could you try v2.0.x?

**Comment by dovanmanh080485** [comment]
Hello @cjyclaire  thanks for your reply


Yes i am using v2.0.x and send 2.5. I am flowing this this link https://framework.zend.com/manual/2.1/en/modules/zend.session.manager.html for setting session handler. 
if (isset($session['save_handler'])) {
                            // class should be fetched from service manager since it will require constructor arguments
                            $sessionSaveHandler = $sm->get($session['save_handler']);
                        }else{
// here my code
 $sessionSaveHandler =  $sm->get(DynamoDbSaveHandler::class); 

 }

Am I right way ?

**Comment by dovanmanh080485** [comment]
@cjyclaire  Hello, 

it's my mistake. it's fixed. 
thanks.

**Comment by dovanmanh080485** [comment]
@cjyclaire Hello new week.
exactly, i'm using version

**Comment by jarrettj** [comment]
How did you fix it @cjyclaire ?

**Comment by dovanmanh080485** [comment]
@jarrettj it's wrong version.

**Comment by jarrettj** [comment]
Thanks @dovanmanh080485. Changed to latest version :)
