### ISSUE TITLE
ZF3 support

### ISSUE THREAD

**Issue by jarrettj** [aws/aws-sdk-php-zf2#44]
Hi,

Good day, and thanks for the cool module.

Any plans to port to ZF3? Thanks.

**Comment by cjyclaire** [comment]
@jarrettj Appreciate the feedback! I'll list it in our backlog. 
Meanwhile, you're free to create a PR for it for us to review :)

**Comment by jarrettj** [comment]
Thank you @cjyclaire! I'll give it a go :)

**Comment by cjyclaire** [comment]
Closing, tracking with #45 instead :)
