### ISSUE TITLE
Zend Framework 3.0 support

### ISSUE THREAD

**Issue by TomHAnderson** [aws/aws-sdk-php-zf2#47]
With the recent release of Zend Framework 3.0 this library no longer supports a compatible repository list.  That is, with this module as a dependency it is not possible to install Zend Framework 3.0.  This is an issue for my ability to develop into the future.

This library will no longer represent its name.  However the latest release remarked support for 3.0 was now included.

I recommend you retire this module to Zend Framework 2 and create a new module called aws-sdk-php-zendframework to support the development of Zend Framework going forward.   

Please consider this a high priority so we can start using the latest from Zend with the latest from AWS.

**Comment by guilherme90** [comment]
https://github.com/aws/aws-sdk-php-zf2/commit/012ce4c500c00b4558ae8b4a590e2cd152153e62

Not work ?
