### ISSUE TITLE
Release version 4.2

### ISSUE THREAD

**Issue by ethanbray** [aws/aws-sdk-php-zf2#62]
The version constraint for `zend-filter` was updated in this commit https://github.com/aws/aws-sdk-php-zf2/commit/f8391226a292ea4ce2ef437223e0e91c8a0bf6c2. However a release has not been tagged since then and as a result I cannot use `zend-filter` version 2.9 in my application alongside this library.

**Comment by diehlaws** [comment]
Thanks for reaching out to us about this @ethanbray. Unfortunately releases for this utility are not automated, however we'll be pushing a new tagged release for this soon.

**Comment by howardlopez** [comment]
@ethanbray [Version 4.2.0](https://github.com/aws/aws-sdk-php-zf2/releases/tag/4.2.0) has been released with that commit. Thanks for the heads-up.
